const SlideTypes = {
  ACCOUNT_SELECTION: "ACCOUNT_SELECTION",
  ACTIVATE_CLOUD_LICENSE: "ACTIVATE_CLOUD_LICENSE",
  ACTIVATE_LICENSE: "ACTIVATE_LICENSE",
  NEW_VS_RETURNING: "NEW_VS_RETURNING",
  SUMMARY: "SUMMARY",
  TABLE_TUTORIAL: "TABLE_TUTORIAL",
  USER_TYPE: "USER_TYPE",
  WELCOME: "WELCOME",
};

const TableCaptureExperience = {
  NEW_USER: "NEW_USER",
  RETURNING_USER: "RETURNING_USER",
};
