name: Update Branch

on:
  push: 
    branches: 
      - main
      - test*

jobs:
  build-runspace:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Create local changes
      run: |
        powershell.exe -f CompileOfficeUtil.ps1
    - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Compile Office Utility
